In [1]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import confusion_matrix, roc_curve, auc, accuracy_score
from xgboost import XGBClassifier

from huggingface_hub import hf_hub_download

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('C:\\Users\\vrish\\Documents\\Humber\\project\\Tech-Troopers\\Common\\results_temp\\reg_cat\\xgboost-results\\Brazilian_houses.csv')
df.dropna(axis=1, how='all')
df.head()

,val_r2_score,test_r2_score,train_r2_score,objective,base_score,booster,callbacks,colsample_bylevel,colsample_bynode,colsample_bytree,...,reg_alpha,reg_lambda,sampling_method,scale_pos_weight,subsample,tree_method,validate_parameters,verbosity,alpha,lambda
0,0.988728,0.995812,0.999828,reg:squarederror,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',b''
1,0.989170,0.992398,0.984861,reg:squarederror,NaN,NaN,NaN,0.886105,NaN,0.541322,...,NaN,NaN,NaN,NaN,0.845843,NaN,NaN,NaN,0.0006128029418768344,2.6466978107531776
2,0.992187,0.996706,0.999806,reg:squarederror,NaN,NaN,NaN,0.740134,NaN,0.939859,...,NaN,NaN,NaN,NaN,0.875559,NaN,NaN,NaN,0.0004307649176543547,1.463045358283812
3,0.988658,0.997185,0.998499,reg:squarederror,NaN,NaN,NaN,0.645138,NaN,0.618580,...,NaN,NaN,NaN,NaN,0.916843,NaN,NaN,NaN,6.654305443081163e-05,3.655991114762573
4,0.990914,0.995506,0.991122,reg:squarederror,NaN,NaN,NaN,0.706516,NaN,0.911832,...,NaN,NaN,NaN,NaN,0.528224,NaN,NaN,NaN,4.272870845019707,3.157789837652969

In [3]:
df[df.columns[:3]] = df[df.columns[:3]].apply(pd.to_numeric)

In [4]:
for col in df.select_dtypes(include=['object']).columns :
	print(f'Col - {col} : {df[col].unique()}')

Col - objective : ['reg:squarederror']
Col - alpha : ["b''" '0.0006128029418768344' '0.0004307649176543547'
 '6.654305443081163e-05' '4.272870845019707' '0.26289180378048604'
 '1.3186646167814866e-08' '8.941014355350942e-07' '0.02957651528246099'
 '3.688701757839663e-05' '2.8735634784611544e-07' '2.2059752964536745e-06'
 '1.2045795769625571' '62.316871250677934' '0.010809728574083022'
 '89.78756536654213' '0.00620308683357447' '0.004110758387777875'
 '2.4363947982892795' '1.095694945511685e-05' '2.4310969051591604e-08'
 '7.866791643476193e-08' '2.1463739568662782e-07' '0.0020917949915075663'
 '3.375128456321451e-05' '0.000394107307251617' '0.009086032829207882'
 '0.5538528930324007' '5.1228072888262227e-08' '4.429366978281781' nan
 '0.005345582638190256']
Col - lambda : ["b''" '2.6466978107531776' '1.463045358283812' '3.655991114762573'
 '3.157789837652969' '1.116354483061185' '1.372906551008989'
 '1.6398729914723817' '1.0579976312977315' '2.972084583616426'
 '3.8193410820289926' '1.5696801759176144' '2.372573149008909'
 '1.5721097402656106' '3.4885341307930195' '3.899478347337514'
 '3.3561014641990266' '3.025672899520666' '1.9206211974281804'
 '1.478119229887754' '1.9409716665652441' '2.162011571125846'
 '3.4307675483524953' '2.3816240490353375' '1.7229216348903345'
 '1.9937856993237797' '2.505086068505594' '1.0808373784360146'
 '2.510928438780139' '2.2945393952521775' nan '1.3988717144617033']